# Generated by Django 4.0.5 on 2022-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_suggestion_other_suggestion_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='opt',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Management Related'), ('3', 'Job Related'), ('4', 'Workplace/Culture'), ('5', 'Other')], default='1', max_length=2, null=True),
        ),
    ]
